### PR TITLE
handle multiple (hex and utf) encodings when unescaping

### PR DESCRIPTION
**Pull request by davishmcclurg**
https://beta.getsentry.com/swiftypecom/work/group/83439497/

### CODE REVIEW

**Comment by davishmcclurg** [comment]
@marshalium do you mind taking a look at this? The root of the problem seems to be that PostRank expects Addressable::URI objects to be normalized before being unescaped (https://github.com/swiftype/postrank-uri/blob/master/lib/postrank-uri.rb#L247).

**Comment by dweinand** [comment]
Having just been deep into this, I don't think the issue has to do with the normalization. Rather, the process of unescaping these codes inherently creates ASCII characters which causes ruby to throw a fit if the string it's trying to merge it into has existing unicode characters.

If you look at [addressable's unencode method](https://github.com/sporkmonger/addressable/blob/master/lib/addressable/uri.rb#L433), you'll see they force the encoding when they unescape too.

In which case, it looks like this PR is doing exactly the right thing.

**Comment by marshalium** [comment]
LGTM!

**Comment by davishmcclurg** [comment]
@dweinand awesome, thanks for looking at this.

**Pull request merged**
